# Generated by Django 3.2.9 on 2021-11-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBancamia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomnbre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('numero_documento', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(choices=[('cc', 'cc'), ('ti', 'ti')], max_length=10)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('ciudad_nacimiento', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
