# Generated by Django 3.2.9 on 2021-11-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbancamia',
            old_name='nomnbre',
            new_name='nombre',
        ),
    ]
